import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import style from '../styles/Home.module.css'
import Link from 'next/link'
import MostReadings from './component/MostReading'
import RightContainer from './component/rightContainer'
import Midcontainer from './component/Midcontainer'
import LeftContainer from './component/LeftContainer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
 
  return (
    <>



      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={style.main}>
<LeftContainer/>
      
    <Midcontainer/>
      
       <RightContainer/>
      </main>
      <MostReadings/>
      

    </>
  

  )
}
